# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
gems:                [jekyll-paginate]
permalink:           pretty
#relative_permalinks: true

# Setup
title:               notes
tagline:             'programming'
description:         '미치도록 잘하고싶다'
url:                 http://smilejp.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              jp
  url:               https://twitter.com/smilejp
  email:             smile.wjp@gmail.com

# Custom vars
version:             1.0.0
